<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="title">عنوان</label><input class="form-control" id="title" name="title" value="{{ old('title', $item?->title) }}" required></div>
    <div class="col-md-3"><label class="form-label" for="type">نوع لینک</label><select class="form-control" id="type" name="type" required>@foreach ($types as $type)<option value="{{ $type }}" @selected(old('type', $item?->type ?? 'custom') === $type)>{{ $type }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label" for="target">باز شدن لینک</label><select class="form-control" id="target" name="target"><option value="_self" @selected(old('target', $item?->target ?? '_self') === '_self')>همین پنجره</option><option value="_blank" @selected(old('target', $item?->target) === '_blank')>تب جدید</option></select></div>
    <div class="col-md-6"><label class="form-label" for="url">لینک خارجی یا دستی</label><input class="form-control" dir="ltr" id="url" name="url" value="{{ old('url', $item?->url) }}" placeholder="https://example.com یا /pages/sample"></div>
    <div class="col-md-6"><label class="form-label" for="route_name">انتخاب صفحه داخلی</label><select class="form-control" id="route_name" name="route_name"><option value="">بدون route داخلی</option>@foreach ($internalRoutes as $routeName => $label)<option value="{{ $routeName }}" @selected(old('route_name', $item?->route_name) === $routeName)>{{ $label }} ({{ $routeName }})</option>@endforeach</select><small class="text-muted">بعداً به مدل‌های Page/Post/Union قابل اتصال است.</small></div>
    <div class="col-md-4"><label class="form-label" for="reference_type">نوع مرجع</label><input class="form-control" dir="ltr" id="reference_type" name="reference_type" value="{{ old('reference_type', $item?->reference_type) }}" placeholder="Page, Post, Union..."></div>
    <div class="col-md-4"><label class="form-label" for="reference_id">شناسه مرجع</label><input class="form-control" dir="ltr" id="reference_id" name="reference_id" type="number" min="1" value="{{ old('reference_id', $item?->reference_id) }}"></div>
    <div class="col-md-4"><label class="form-label" for="parent_id">انتخاب والد</label><select class="form-control" id="parent_id" name="parent_id"><option value="">بدون والد</option>@foreach ($parents as $parent)<option value="{{ $parent->id }}" @selected((string) old('parent_id', $item?->parent_id) === (string) $parent->id)>{{ $parent->title }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label" for="icon">آیکون</label><input class="form-control" id="icon" name="icon" value="{{ old('icon', $item?->icon) }}" placeholder="مثلاً 📰 یا کلاس آیکون"></div>
    <div class="col-md-4"><label class="form-label" for="sort_order">ترتیب</label><input class="form-control" dir="ltr" id="sort_order" name="sort_order" type="number" min="0" value="{{ old('sort_order', $item?->sort_order ?? 0) }}"></div>
    <div class="col-md-4"><label class="form-label" for="is_active">وضعیت فعال</label><select class="form-control" id="is_active" name="is_active"><option value="1" @selected((string) old('is_active', $item?->is_active ?? 1) === '1')>فعال</option><option value="0" @selected((string) old('is_active', $item?->is_active ?? 1) === '0')>غیرفعال</option></select></div>
</div>
<div class="admin-form-actions"><button class="admin-primary-btn" type="submit">ذخیره آیتم</button><a class="admin-secondary-btn" href="{{ route('admin.menus.show', $menu) }}">انصراف</a></div>
