@extends('admin.layouts.app')
@section('title', 'جزئیات کمیسیون')
@section('content')
<div class="admin-page-toolbar"><div><p class="admin-eyebrow">کمیسیون‌ها</p><h2>{{ $commission->title }}</h2></div><div class="admin-actions"><a class="admin-secondary-btn" href="{{ route('admin.commissions.index') }}">بازگشت</a><a class="admin-secondary-btn" href="{{ route('admin.commissions.sessions.index', $commission) }}">جلسات</a>@if(request()->user()->hasPermission('commissions.edit'))<a class="admin-primary-btn" href="{{ route('admin.commissions.edit', $commission) }}">ویرایش</a>@endif</div></div>
<div class="admin-panel-card"><div class="row g-4"><div class="col-md-4">@if($commission->image)<img src="{{ Storage::url($commission->image) }}" alt="{{ $commission->title }}" style="width:100%;height:260px;object-fit:cover;border-radius:18px">@endif</div><div class="col-md-8"><p><strong>نامک:</strong> <span dir="ltr">{{ $commission->slug }}</span></p><p><strong>وضعیت:</strong> {{ $commission->status_label }}</p><p><strong>فعال:</strong> {{ $commission->is_active ? 'بله' : 'خیر' }}</p><p><strong>ترتیب:</strong> {{ $commission->sort_order }}</p></div></div></div>
<div class="admin-panel-card mt-3"><h3>اعضا</h3>@forelse($commission->members ?? [] as $member)<span class="admin-badge">{{ $member['name'] ?? '' }}</span>@empty<p class="text-muted">عضوی ثبت نشده است.</p>@endforelse</div>
<div class="admin-panel-card mt-3"><h3>توضیحات</h3><div>{!! nl2br(e($commission->description ?: '—')) !!}</div></div>
@if(!empty($commission->attachments))<div class="admin-panel-card mt-3"><h3>پیوست‌ها</h3>@foreach($commission->attachments as $file)<p><a href="{{ Storage::url($file['path'] ?? '') }}" target="_blank">{{ $file['name'] ?? 'دانلود فایل' }}</a></p>@endforeach</div>@endif
<div class="admin-panel-card mt-3"><h3>آخرین جلسات</h3>@forelse($commission->sessions as $session)<p><a href="{{ route('admin.commissions.sessions.show', [$commission,$session]) }}">{{ $session->title }}</a> - {{ $session->session_date?->format('Y/m/d H:i') ?: 'بدون تاریخ' }}</p>@empty<p class="text-muted">جلسه‌ای ثبت نشده است.</p>@endforelse</div>
@endsection
