@extends('frontend.layouts.app')
@section('title', $commission->title.' | کمیسیون‌ها')
@section('meta_description', Str::limit(strip_tags($commission->description), 160))
@section('frontend_variant', 'compact')
@section('footer_links_variant', 'short')
@section('content')
<section class="page-header page-header-alt"><div class="site-container"><h1>{{ $commission->title }}</h1><nav class="breadcrumb"><a href="{{ route('home') }}">خانه</a><a href="{{ route('commissions.index') }}">کمیسیون‌ها</a><span>{{ $commission->title }}</span></nav></div></section>
<section class="site-container"><div class="news-single-layout"><article class="news-single-main">@if($commission->image)<div class="news-single-cover"><img src="{{ Storage::url($commission->image) }}" alt="{{ $commission->title }}" loading="lazy"></div>@endif<div class="news-single-body"><h2>{{ $commission->title }}</h2><p>{!! nl2br(e($commission->description ?: 'توضیحات این کمیسیون هنوز تکمیل نشده است.')) !!}</p></div><div class="admin-panel-card mt-4"><h3>وظایف کمیسیون</h3>@forelse($commission->activeTasks as $task)<div class="related-post-item" style="align-items:flex-start"><div><strong>{{ $task->title }}</strong><p>{{ $task->description ?: 'توضیحی برای این وظیفه ثبت نشده است.' }}</p></div></div>@empty<p class="text-muted">وظیفه‌ای برای این کمیسیون ثبت نشده است.</p>@endforelse</div><div class="admin-panel-card mt-4"><h3>اعضای کمیسیون</h3>@forelse($commission->members ?? [] as $member)<span class="post-tag">{{ $member['name'] ?? '' }}</span>@empty<p class="text-muted">اعضایی برای نمایش ثبت نشده است.</p>@endforelse</div>@if(!empty($commission->attachments))<div class="admin-panel-card mt-4"><h3>پیوست‌ها</h3>@foreach($commission->attachments as $file)<p><a class="post-tag" href="{{ Storage::url($file['path'] ?? '') }}" target="_blank">{{ $file['name'] ?? 'دانلود فایل' }}</a></p>@endforeach</div>@endif<div class="admin-panel-card mt-4"><h3>جلسات کمیسیون</h3>@forelse($commission->publishedSessions as $session)<div class="related-post-item" style="align-items:flex-start"><div><strong>{{ $session->title }}</strong><span>{{ jalali_datetime($session->session_date) ?: 'بدون تاریخ' }}</span><p>{{ Str::limit(strip_tags($session->description), 140) }}</p>@if($session->minutes_file)<a class="post-tag" href="{{ Storage::url($session->minutes_file) }}" target="_blank">دانلود صورتجلسه</a>@endif</div></div>@empty<p class="text-muted">جلسه منتشرشده‌ای برای این کمیسیون وجود ندارد.</p>@endforelse</div></article><aside class="news-sidebar"><div class="news-sidebar-card"><h4>اطلاعات کمیسیون</h4><p>تعداد اعضا: {{ count($commission->members ?? []) }}</p><p>تعداد جلسات: {{ $commission->publishedSessions->count() }}</p><a class="tab-pill" href="{{ route('commissions.index') }}">بازگشت به کمیسیون‌ها</a></div></aside></div></section>
@endsection
