@extends('admin.layouts.app')

@section('title', 'مدیریت پیام‌های تبریک')

@section('content')
<div class="admin-page-toolbar"><div><p class="admin-eyebrow">پیام‌های تبریک</p><h2>مدیریت پیام‌های تبریک مدیران اصناف</h2></div>@if(request()->user()->hasPermission('congratulation_messages.create'))<a class="admin-primary-btn" href="{{ route('admin.congratulation_messages.create') }}">ایجاد پیام جدید</a>@endif</div>
<div class="admin-panel-card mb-3"><form class="admin-search-form" action="{{ route('admin.congratulation_messages.index') }}" method="GET"><label class="form-label mb-0">جستجو</label><input class="form-control" name="search" value="{{ $search }}" placeholder="عنوان، نامک، نام مدیر یا متن پیام..."><select class="form-control" name="union_id"><option value="">همه / عمومی</option>@foreach($unions as $union)<option value="{{ $union->id }}" @selected((string)$unionId===(string)$union->id)>{{ $union->display_title }}</option>@endforeach</select><select class="form-control" name="status"><option value="">همه وضعیت‌ها</option>@foreach($statusLabels as $value=>$label)<option value="{{ $value }}" @selected($status===$value)>{{ $label }}</option>@endforeach</select><button class="admin-primary-btn">اعمال فیلتر</button><a class="admin-secondary-btn" href="{{ route('admin.congratulation_messages.index') }}">حذف فیلتر</a></form></div>
<div class="admin-panel-card"><div class="table-responsive"><table class="admin-table"><thead><tr><th>عنوان</th><th>مدیر</th><th>اتحادیه</th><th>نمایش</th><th>وضعیت</th><th>ترتیب</th><th>عملیات</th></tr></thead><tbody>@forelse($messages as $message)<tr><td><strong>{{ $message->title }}</strong><br><small dir="ltr">{{ $message->slug }}</small></td><td>{{ $message->manager_name ?: '—' }}<br><small>{{ $message->manager_position ?: '—' }}</small></td><td>{{ $message->union?->display_title ?: 'عمومی' }}</td><td><small>خانه: {{ $message->show_on_home ? 'بله' : 'خیر' }} / اتحادیه: {{ $message->show_on_union_page ? 'بله' : 'خیر' }}</small></td><td>{{ $message->status_label }} / {{ $message->is_active ? 'فعال' : 'غیرفعال' }}</td><td>{{ $message->sort_order }}</td><td><div class="admin-actions"><a class="admin-secondary-btn" href="{{ route('admin.congratulation_messages.show', $message) }}">نمایش</a>@if(request()->user()->hasPermission('congratulation_messages.edit'))<a class="admin-secondary-btn" href="{{ route('admin.congratulation_messages.edit', $message) }}">ویرایش</a>@endif @if(request()->user()->hasPermission('congratulation_messages.delete'))<form action="{{ route('admin.congratulation_messages.destroy', $message) }}" method="POST">@csrf @method('DELETE')<button class="admin-danger-btn">حذف</button></form>@endif</div></td></tr>@empty<tr><td colspan="7" class="text-center text-muted">پیام تبریکی ثبت نشده است.</td></tr>@endforelse</tbody></table></div>{{ $messages->links() }}</div>
@endsection
