@extends('frontend.layouts.app')
@section('title', ($union->display_title ?? $union->title ?? 'اتحادیه صنفی').' | اتاق اصناف مرکز استان گلستان')
@section('meta_description', $union->meta_description ?? $union->short_description ?? 'اطلاعات اتحادیه صنفی')
@section('content')
<div class="guild-hero">
<img alt="{{ $union->display_title }}" class="guild-hero-bg" src="{{ asset($union->cover_image ?? 'assets/img/asnaf-gorgan-default.jpg') }}"/>
<div class="site-container guild-hero-content">
<div class="guild-hero-logo">{{ mb_substr($union->name ?? $union->title ?? 'ا',0,1) }}</div>
<div class="guild-hero-text">
<nav class="breadcrumb-nav" style="margin-bottom:10px"><a href="{{ route('home') }}" style="color:rgba(255,255,255,.6)">خانه</a><span class="breadcrumb-sep">/</span><a href="{{ route('guilds.index') }}" style="color:rgba(255,255,255,.6)">اتحادیه‌ها</a><span class="breadcrumb-sep">/</span><span style="color:rgba(255,255,255,.8)">{{ $union->display_title }}</span></nav>
<h1>{{ $union->display_title }}</h1><p>{{ $union->short_description ?? 'اتحادیه فعال زیرمجموعه اتاق اصناف مرکز استان گلستان' }}</p>
<div class="guild-hero-stats"><span>اعضا: <strong>{{ $members->count() }}</strong></span><span>وضعیت: <strong>{{ $union->is_active ? 'فعال' : 'غیرفعال' }}</strong></span><span>آخرین بروزرسانی: <strong>{{ jalali_date($union->updated_at) }}</strong></span></div>
</div></div></div>
<main><div class="site-container guild-layout"><aside class="guild-side-nav"><h4>راهنمای سریع</h4><ul><li><a href="#guild-members">اعضا</a></li><li><a href="#guild-news">آخرین اخبار</a></li><li><a href="#guild-announce">اطلاعیه‌ها</a></li><li><a href="#guild-gallery">گالری و ویدیو</a></li><li><a href="#guild-complaint">ثبت شکایت صنفی</a></li><li><a href="#guild-contact">تماس با ما</a></li></ul></aside><div>
<section class="guild-section guild-section-alt" id="guild-members" style="padding-top:0"><h3 class="guild-section-title">رییس اتحادیه</h3><div class="guild-head-card"><div class="guild-head-avatar">{{ mb_substr($union->manager_name ?? 'م',0,1) }}</div><div class="guild-head-info"><strong>{{ $union->manager_name ?? 'مدیر اتحادیه' }}</strong><span>رییس {{ $union->name }}</span><p>{{ $union->description ?? 'اطلاعات این اتحادیه از پایگاه داده خوانده می‌شود.' }}</p><div class="guild-head-contact"><a href="tel:{{ $union->phone }}">تماس با اتحادیه</a><a href="#guild-contact">اطلاعات تماس</a></div></div></div></section>
@if($union->members_enabled)<section class="guild-section guild-section-alt" id="guild-members-list"><h3 class="guild-section-title">اعضای فعال اتحادیه</h3><div class="guild-members-grid">@forelse($members as $member)<div class="guild-member-card"><div class="member-avatar">{{ mb_substr($member->full_name,0,1) }}</div><strong>{{ $member->full_name }}</strong><small>{{ $member->business_name }} - {{ $member->membership_code }}</small></div>@empty<div class="guild-member-card"><strong>عضوی ثبت نشده است</strong><small>پس از ثبت اعضا نمایش داده می‌شود</small></div>@endforelse</div></section>@endif
@if($union->news_enabled)<section class="guild-section" id="guild-news"><h3 class="guild-section-title">آخرین اخبار</h3><div class="guild-news-list">@forelse($posts as $post)<a class="guild-news-item" href="{{ route('posts.show',$post->slug) }}"><img alt="{{ $post->title }}" src="{{ asset($post->featured_image ?? 'assets/img/asnaf-gorgan-default.jpg') }}"/><div><strong>{{ $post->title }}</strong><small>{{ jalali_date($post->published_at) }}</small><p>{{ $post->excerpt }}</p></div></a>@empty<p>خبری برای این اتحادیه ثبت نشده است.</p>@endforelse</div></section>@endif
@if($union->announcements_enabled)<section class="guild-section guild-section-alt" id="guild-announce"><h3 class="guild-section-title">اطلاعیه‌ها و بخشنامه‌ها</h3><div class="guild-rules-list">@forelse($announcements as $announcement)<a class="guild-rule-item" href="{{ route('announcements.show',$announcement->slug) }}"><div class="rule-icon">📋</div><div><strong>{{ $announcement->title }}</strong><small>{{ $announcement->excerpt }}</small></div></a>@empty<p>اطلاعیه‌ای ثبت نشده است.</p>@endforelse</div></section>@endif
@if($union->gallery_enabled || $union->videos_enabled)<section class="guild-section" id="guild-gallery"><h3 class="guild-section-title">گالری تصاویر و ویدیو</h3><div class="guild-members-grid">@foreach($galleries as $gallery)<a class="guild-member-card" href="{{ route('galleries.show',$gallery->slug) }}"><div class="member-avatar">🖼</div><strong>{{ $gallery->title }}</strong><small>{{ $gallery->images_count }} تصویر</small></a>@endforeach @foreach($videos as $video)<a class="guild-member-card" href="{{ route('videos.show',$video->slug) }}"><div class="member-avatar">▶</div><strong>{{ $video->title }}</strong><small>ویدیو</small></a>@endforeach</div></section>@endif
@if($union->congratulations_enabled && $congratulationMessages->isNotEmpty())<section class="guild-section guild-section-alt"><h3 class="guild-section-title">پیام‌های تبریک</h3>@foreach($congratulationMessages as $message)<div class="guild-head-card"><div class="guild-head-avatar">🎉</div><div class="guild-head-info"><strong>{{ $message->title }}</strong><span>{{ $message->manager_name }}</span><p>{!! $message->body !!}</p></div></div>@endforeach</section>@endif
<section class="guild-section" id="guild-complaint"><h3 class="guild-section-title">ثبت شکایت صنفی</h3><div class="guild-head-card"><div class="guild-head-info"><p>برای ثبت شکایت مرتبط با این اتحادیه از فرم الکترونیکی استفاده کنید.</p><div class="guild-head-contact"><a href="{{ route('complaints.create',['union_id'=>$union->id]) }}">ثبت شکایت</a><a href="{{ route('complaints.track') }}">پیگیری شکایت</a></div></div></div></section>
<section class="guild-section guild-section-alt" id="guild-contact"><h3 class="guild-section-title">تماس با ما و شبکه‌های اجتماعی</h3><div class="guild-rules-list"><div class="guild-rule-item"><div class="rule-icon">📍</div><div><strong>آدرس</strong><small>{{ $union->address ?? 'گرگان، ساختمان اتاق اصناف' }}</small></div></div><div class="guild-rule-item"><div class="rule-icon">📞</div><div><strong>تلفن</strong><small>{{ $union->phone ?? '۰۱۷۳۲۱۵۲۹۱۲' }}</small></div></div><div class="guild-rule-item"><div class="rule-icon">✉️</div><div><strong>ایمیل</strong><small>{{ $union->email ?? 'info@asnaf-gorgan.ir' }}</small></div></div>@forelse(($union->social_links ?? []) as $network => $link)@if(filled($link))<a class="guild-rule-item" href="{{ $link }}" target="_blank" rel="noopener"><div class="rule-icon">🔗</div><div><strong>{{ $network }}</strong><small dir="ltr">{{ $link }}</small></div></a>@endif @empty<div class="guild-rule-item"><div class="rule-icon">🔗</div><div><strong>شبکه اجتماعی</strong><small>لینکی برای این اتحادیه ثبت نشده است.</small></div></div>@endforelse</div></section>
</div></div></main>
@endsection
